Repository mdsol/rubycas-client, pull requests merged in 2018-02, with the labels that each got.

#35 MCC-370061-Updated for single sign out
  lib/casclient/tickets/storage/active_model_memcache_ticket_store.rb
  spec/support/shared_examples_for_ticket_stores.rb
Labels: Ready to Merge, Reviewed by Rohan

#36 use the version declared in `lib/casclient/version.rb`
  .travis.yml
  CHANGELOG.md
  Gemfile
  Gemfile.lock
  lib/casclient/version.rb
  rubycas-client.gemspec
Labels: Reviewed by Rod, Reviewed by Rohan

#37 Develop to Master to Tag v3.0.1
  .travis.yml
  CHANGELOG.md
  Gemfile
  Gemfile.lock
  lib/casclient/tickets/storage/active_model_memcache_ticket_store.rb
  lib/casclient/version.rb
  rubycas-client.gemspec
  spec/support/shared_examples_for_ticket_stores.rb
Labels: Ready to Merge, Reviewed by Rohan, Reviewed by Shahid

#34 Added documentation to use Memcached for CAS
  README.rdoc
  templates/active_model_memcache_store.rb
Labels: Reviewed by Rod, Reviewed by Shahid
